[GeneralSettings]

# Range for sleep time after successful bridge (seconds)
WalletDelayRange = [30, 100] 

# Range for sleep time after failed action (seconds)
AfterFailDelayRange = [5, 10]

# The source chain for bridges
# Possible values: "Arbitrum", "Optimism", "Base", "Linea", "Scroll"
SrcChain = ""

# The destination chain for bridges
# Possible values are the same as for SrcChain
DstChain = ""

# Bridge mode ("BUS"/"TAXI")
StargateBridgeMode = "BUS"

# Percentage of ETH balance that will be used as bridge amount
# Ignored if UseFullBridge = true
BalancePercentageToBridge = [70, 80]

# If true, picked bridge amount will include all fees (true/false)
IncludeFees = false

# If true, script will try to bridge whole ETH balance (true/false)
UseFullBridge = false

[RpcEndpoints]

ERC20 = "https://rpc.ankr.com/eth"
Arbitrum = "https://rpc.ankr.com/arbitrum"
Optimism = "https://rpc.ankr.com/optimism"
Linea = "https://rpc.linea.build"
Scroll = "https://rpc.ankr.com/scroll"
Base = "https://rpc.ankr.com/base"